### ISSUE TITLE
Enganchar registro y login de movil con backend + pantallas ajustes

### ISSUE THREAD

**Issue by dmarcob** [UNIZAR-30226-2021-05/SeguimientoEsfuerzos#8]

**Comment by SergioHer** [comment]
Realizado.

Se ha implementado:

- Conectar registro con Backend
- Conectar login con backend
- Guardar la sesión del usuario hasta que cierra sesión o se desinstala la aplicación.
- Cerrar la sesión.
- Se han hecho todas las pantallas de ajustes
-  SE HA INTENTADO CONECTAR CON UN _IMAGEPICKER_ PARA SUBIR FOTOS DESDE LA GALERIA O DESDE LA CAMARA (TODAVÍA NO SE HA CONSEGUIDO)
- Se han resizeado las pantallas de Login y Registro.
- Se han tratado todos errores de la app hasta el momento (contraseñas incorrectas, contraseñas no coinciden, y más aspectos de seguridad)
- Se ha decidido hasta este punto no encriptar las contraseñas desde la app (veremos en el futuro)
-
